/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef student_TYPES_H
#define student_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace lj { namespace test {

class student;

typedef struct _student__isset {
  _student__isset() : sno(false), name(false), ssex(false), sage(false) {}
  bool sno :1;
  bool name :1;
  bool ssex :1;
  bool sage :1;
} _student__isset;

class student {
 public:

  student(const student&);
  student& operator=(const student&);
  student() : sno(0), name(), ssex(0), sage(0) {
  }

  virtual ~student() throw();
  int32_t sno;
  std::string name;
  bool ssex;
  int16_t sage;

  _student__isset __isset;

  void __set_sno(const int32_t val);

  void __set_name(const std::string& val);

  void __set_ssex(const bool val);

  void __set_sage(const int16_t val);

  bool operator == (const student & rhs) const
  {
    if (!(sno == rhs.sno))
      return false;
    if (!(name == rhs.name))
      return false;
    if (!(ssex == rhs.ssex))
      return false;
    if (!(sage == rhs.sage))
      return false;
    return true;
  }
  bool operator != (const student &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const student & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(student &a, student &b);

inline std::ostream& operator<<(std::ostream& out, const student& obj)
{
  obj.printTo(out);
  return out;
}

}} // namespace

#endif
