[package]
name = "hello"
version = "0.1.0"
authors = ["evilsmile <freedominmind@163.com>"]
edition = "2018"

[dependencies]
hello_macro = { path = "../hello_macro" }
hello_macro_derive = { path = "../hello_macro_derive" }
